import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

/// Maps GBIF taxon keys to built-in catalog species, and supplies the taxon
/// whitelist used to filter the occurrence query.
///
/// Both come from `assets/data/species_gbif_keys.json`, generated by
/// `tool/generate_species_gbif_keys.dart`. Deriving the whitelist from the
/// catalog makes it complete by construction: no catalog species can be
/// filtered out, and birds, insects and terrestrial plants are excluded
/// because none appear in the catalog.
///
/// The keys are deliberately mixed-rank rather than all orders. Most are
/// orders, which are aquatic wholesale; marine carnivores enter at genus so
/// that Carnivora does not drag in foxes and badgers, and sea turtles enter
/// at family because GBIF gives them no order key. The generator explains
/// the choice per rank.
class SpeciesCatalogMatcher {
  final Map<int, String> _byGbifKey;
  final List<int> _taxonKeys;

  const SpeciesCatalogMatcher._(this._byGbifKey, this._taxonKeys);

  static SpeciesCatalogMatcher? _cached;

  static Future<SpeciesCatalogMatcher> load() async {
    final cached = _cached;
    if (cached != null) return cached;

    final raw = await rootBundle.loadString(
      'assets/data/species_gbif_keys.json',
    );
    return _cached = fromJsonString(raw);
  }

  /// Visible for testing so the matcher can be built without an asset bundle.
  static SpeciesCatalogMatcher fromJsonString(String raw) {
    final json = jsonDecode(raw) as Map<String, dynamic>;
    final keys = (json['speciesKeys'] as Map).map(
      (k, v) => MapEntry(int.parse(k as String), v as String),
    );
    final taxa = (json['taxonKeys'] as List).cast<int>();
    return SpeciesCatalogMatcher._(keys, List.unmodifiable(taxa));
  }

  /// Clears the cache. Testing only.
  static void resetCache() => _cached = null;

  String? localIdFor(int gbifKey) => _byGbifKey[gbifKey];

  /// Mixed-rank GBIF keys, passed to the occurrence query as `taxonKey`.
  List<int> get taxonKeys => _taxonKeys;
}
